### ISSUE TITLE
Outlinekosmetik

### ISSUE THREAD

**Issue by DonMaso** [wingworks/Circus-11#1]
Min. Änderungsvorschläge, siehe file. Wenn möglich, würde ich gerne den Unterschied zu 4.0 als 4.1 in 3D sehen. Sweep unverändert, TE nach Strut 3/4 leicht verändert.
Arc macht bei Segment 0 etwas mehr auf und ist nach Strut 3/4 etwas steiler.
Veränderte Werte in [rot] mit gelber Hinterlegung.

Alle anderen Werte bleiben gleich, d.h., der Kite wird etwas kleiner, was nicht stört, im Gegenteil.

AoA und PT kommen separat. 

[Comments Karsten Circus 4.0 Teil 1.xls.pdf](https://github.com/wingworks/Circus-11/files/636469/Comments.Karsten.Circus.4.0.Teil.1.xls.pdf)

**Comment by karsteng** [comment]
OK, das passe ich an für Version 0.5.

**Comment by wingworks** [comment]
Habe die Winkel im Center für Version 0.5 angepasst. Geringe Abweichungen zu den Vorgaben durch automatische Winkelberechnung. Siehe Datei [Circus-11.txt](https://github.com/wingworks/Circus-11/files/643279/Circus-11.txt)
Tips wandern dadurch etwas weiter nach oben
TE und sweep unverändert gelassen.
![issue_1](https://cloud.githubusercontent.com/assets/18679769/21065763/4d00c926-be62-11e6-8a89-3982bc5dda12.png)
Version 0.4 in grau, Version 0.5 in farbe

**Comment by DonMaso** [comment]
Super, wir sind in der Kosmetik! :)

Chord/TE am unverändert zwischen 4.0 und 5.0, i.e. doch grösseres “Ohr”, weniger “cut-out nach Strut 2/3?

**Comment by wingworks** [comment]
Wenn ich deine Tabelle (Link oben) richtig verstanden habe ist die Tiefe ca. 1-2cm geringer nach dem 3. Strut und ganz außen wieder identisch. Das ist nur ein optischer Unterschied. Wenn dann müssen wir den Tip verkürzen. Geht dann allerdings etwas zu Lasten des Drehverhaltens.

**Comment by DonMaso** [comment]
D'accord!

**Comment by wingworks** [comment]
Also lasse ich es wie es ist?

**Comment by DonMaso** [comment]
Deine Entscheidung, Karsten. Ich wollte nur 11er langsamer als 14er machen. 14er hat wieder grösseres Ohr (relativ), damit sie in etwas gleich reagieren.

**Comment by DonMaso** [comment]
Gerne seh ich mir graphisch / auf 3D den Unterschied an :)

**Comment by wingworks** [comment]
OK, dann bleibt es so.
Mehr lässt sich am 3D Modell nicht mehr optimieren. Jetzt muss ein Prototyp her.

**Comment by DonMaso** [comment]
Let’s shoot, einverstanden! Ich bin geistig schon am Ende :)

Bin gespannt, wie dir meine Werte für den 14er (v.4.2) gefallen (AR constant zu 11er)
