### ISSUE TITLE
Profile Depth und AoA

### ISSUE THREAD

**Issue by DonMaso** [wingworks/Circus-11#2]
Da der Tube-Ø fest steht, nun zu „aoa“ und „profile depth“:

1)	AoA:

Mein Verständnis, der Verlauf der Werte für “aoa (profile)” [Definition ??] ergibt Werte für “aoa (Profilnase)”.

Die Werte für “aoa (Profilnase)” liegen nun zwischen 6% (segment-0) und 9%  (segment-8 bzw. Tube 4/5).   Ich komme zurück auf dein anfängliches Argument, bevor ich wusste, dass wir hier unterschiedliche Definitionen haben, dass die von mir reklamierte AoA zu hoch ist, und der Kite ständig knapp an oder in backstall sein wird.

Mein  „revidierter“ Vorschlag ist daher, die „aoa (profile)“ so zu verändern, dass die Werte für “aoa (Profilnase)“ im Bereich der angegebenen Zielwerte bewegen (siehe Range im pdf-file zwischen 4.5 und ca. 6.5 Grad).

Eine Frage dazu, wie verhalten sich die Sprünge der „aoa (profile)“ im Vergleich zu den Sprüngen „aoa (Profilnase)“? 

Exkurs, du hast einen in der Größe vergleichbar Kite, GO mit 12m2, in deinem System.  Was kommen denn für die bestehenden Werte von „aoa (profile)“ für Werte „aoa (Profilnase)“ heraus und wie fliegt sich der Kite?  Wenn du den GO 12m2 noch nicht geflogen bist, was kommt denn für die anderen, von dir geflogenen Kites heraus? Mein Verständnis, du hast natürlich Erfahrungswerte für die bis jetzt benutzen Werte der "aoa (profile)". Wenn du dir nun die Vergleichswerte für "aoa (Profilnase)" ansiehst, welche Werte sind denn nun "flott/wenig pull" oder weniger "flott/starker pull")?

2)	Profile Depth

Zu Profile Depth gibt es a) die Vermessung der 2 „production“ Kites (Wake mit 14m2 und Wave mit 11m2) und b) die Daten im Netz.  Ich habe mich mal am 14m2 Wake-Kite orientiert und, aufgrund der geringeren Größe, ca. 1% abgezogen.  Die vermessenen Daten sind in der letzten Spalte für die Segmente mit Struts (0/5/8) angegeben (grün hinterlegt).

Interessant für uns sind v.a. das segment-0 (Strut-1) und segment-5 (Strut 2/3).  Die Profiltiefe bei Strut 4/5 ist mE sekundär, da das Profil an dieser Stelle mit deinem Wert für „profile depht (profile)“ besser eingestellt werden kann/flach ist bzw die Tube / der Tube-Ø mehr verfälscht.   

Umgekehrt, für Position segment-0 und segment-5 ist der Wert inkl. Tube sehr interessant - Tube-Ø zischen segment-0 und segement-5 reduziert sich um ca. 2cm.

Wenn ich von dir ein dwg der beiden Profile erhalten könnte, kann ich Werte für „profile depth (profile)“ aus den Zielwerten für „profile depth (mit Tube)“ errechnen/zeichnen.   Voraussetzung ist natürlich, dass das dwg die Segmentnaht (die du für "profile depth (profile)" benötigst) und die Strecke für PT-profile eingezeichnet bekomme (90 Grad Winkel auf welche Sehne/Strecke?)!!

Anders formuliert:

Entspricht die Profiltiefe („profile depth (profile)“)  idHv 8% an der Position „segment-0“, bei gegebenem Tub-Ø (170mm) einer „profile depth (mit Tube)“ von 12.8% bis 13.3%?

Entspricht die Profiltiefe („profile depth (profile)“)  idHv 8% an der Position „segment-5“ bei gegebenem Tube-Ø (152mm) einer „profile depth (mit Tube)“ von 11.0% bis 11.5% (inkl. Tube)?

Zum Verlauf, ergeben die Veränderungen von „profile depth (profile)“ idHv ca. 1% - 2% kleinere Sprünge idHv ca. 0.5% für „profile depth (mit Tube)“? 

[Comments Karsten Circus 4.0 Teil 2.xls.pdf](https://github.com/wingworks/Circus-11/files/636678/Comments.Karsten.Circus.4.0.Teil.2.xls.pdf)

**Comment by karsteng** [comment]
Zu 1: 
Die Werte habe ich schon für "weniger flott/starker pull" verändert. Vergleichbar sind sie aber mit meinen anderen Kites nicht da die eine dünnere Tube haben und das natürlich auch Auswirkungen hat.
Höhere AoA Werte würde ich aber im ersten Prototypen nicht einbauen. Backstall ist unangenehmer ls "flott"

**Comment by DonMaso** [comment]
zu 1: 
Ja, glaub ich auch. Deshalb auch der Vorschlag zur Reduzierung :)!

**Comment by DonMaso** [comment]
![circus 4 1 ikdesign](https://cloud.githubusercontent.com/assets/23168314/20985898/af2ac8e2-bcc6-11e6-9d78-587f0c07bc0e.PNG)
![circus 4 1 ik design 3d](https://cloud.githubusercontent.com/assets/23168314/20985899/af2d842e-bcc6-11e6-82f4-aafcbd3fd3a3.PNG)
![circus 4 1 ik design bottom](https://cloud.githubusercontent.com/assets/23168314/20985894/af11a858-bcc6-11e6-8015-0d8441497364.PNG)
![circus 4 1 ik design front](https://cloud.githubusercontent.com/assets/23168314/20985895/af13c692-bcc6-11e6-9806-bea93196d674.PNG)
![circus 4 1 ik design side](https://cloud.githubusercontent.com/assets/23168314/20985896/af16f646-bcc6-11e6-9a9e-0eaa0bc5768a.PNG)
![circus 4 1 surfplan 3d](https://cloud.githubusercontent.com/assets/23168314/20985897/af1c666c-bcc6-11e6-9c8b-23ec71d472c3.PNG)
![circus 4 1 surfplan bottom](https://cloud.githubusercontent.com/assets/23168314/20985900/af3c685e-bcc6-11e6-837b-07156a2056cf.PNG)
![circus 4 1 surfplan front](https://cloud.githubusercontent.com/assets/23168314/20985901/af3e7054-bcc6-11e6-98a4-5ca672d12b27.PNG)
![circus 4 1 surfplan side](https://cloud.githubusercontent.com/assets/23168314/20985902/af45b6d4-bcc6-11e6-8f83-97dc332dee76.PNG)

Ich habe die Werte mal in SurfPlan und IK Design eingegeben. Bei SurfPlan komme ich mit der Tube nicht wirklich hin .. sieht elefantös aus .. :)
IK hingegen sieht sehr gut aus!! :)

**Comment by wingworks** [comment]
Hier noch die Werte der Profildicke. Angefangen in der Mitte:
14,5
14,4
14,3
13,5
13,5
12,4
11,2
10,3
10,5
11,0

**Comment by DonMaso** [comment]
Ahhh, gerade gesehen! 

PT GESAMT, inkl. TUBE?

**Comment by wingworks** [comment]
Genau

**Comment by DonMaso** [comment]
super, danke!!!!


bevor du sie veränderst, lass mich nochmals drüber schlafen, damit du die arbeit nicht zweimal machen musst … :)
Ich werde sie für mich mal zeichnen, alle daten dazu habe ich!

**Comment by wingworks** [comment]
Ich halte die Werte für passend für das Flugverhalten das du erwartest. Daher habe ich sie nicht geändert.

**Comment by DonMaso** [comment]
Eine AoA von ca. 9 … ?  :)

**Comment by DonMaso** [comment]
Die 14.5 sind ok, bei der ersten Strut (2/3) sollte ev. etwas weniger sein und den Verlauf bis zur ersten Strut würde ich “geschmeidiger” machen. 
AoA ist nur hoch, no?!

**Comment by DonMaso** [comment]
Siehe 3D View Vegas:

https://www.northkiteboarding.com/products/kites/vegas/

Wie viel Profil verliert dieser Kite bis zu Strut 2/3?

**Comment by wingworks** [comment]
AoA und Profildicke ist OK, du wolltest ja Zug im Kite :-)
Ist nur unwesentlich mehr als beim GO. Außerdem ist AoA im Center variabel da beweglich um die Querachse.
Profildicke ist "geschmeidig" da sie sich absolut ja ändert durch die Reduzierung der Profillänge.
Profildicke sind wir beim äußeren Strut bei 1% das passt.

**Comment by DonMaso** [comment]
Danke für die Aufklärung!!  Verhältnis Profildicke und Profillänge ist interessant! 
:)

**Comment by DonMaso** [comment]
Interessant müsste die Darstellung einer “Auftriebskraft pro Flächeneinheit” bzw “Auftriebskraft pro projizierter Fläche / mm2” sein ..

**Comment by wingworks** [comment]
... und abhängig vom Anstellwinkel.
Habe ich schon als Funktion in der Software. Ist aber eine theoretische Größe die ich bisher nicht in der Praxis einsetzen bzw. über Messungen am fliegenden Kite überprüfen konnte.

**Comment by DonMaso** [comment]
Klingt gut!  Irgendwann müssen die Werte ja über Funktionen in Auftrieb und Widerstand umgerechnet werden … immerhin, gehts ja darum ..
