### ISSUE TITLE
Profile Depth & AoA (2)

### ISSUE THREAD

**Issue by DonMaso** [wingworks/Circus-11#3]
Kosmetik, wenn es Sinn macht, happy! Wenn nicht, dann nicht! Änderungen sind gelb hinterlegt, veränderte Werte sind rot.

[Comments Karsten Circus 4.0 Teil 3.xls.pdf](https://github.com/wingworks/Circus-11/files/640728/Comments.Karsten.Circus.4.0.Teil.3.xls.pdf)

**Comment by wingworks** [comment]
Profildicke habe ich für 0.5 noch etwas "verrundet" bzw. die Stufen gleichmäßiger gemacht.
AoA unverändert.

**Comment by DonMaso** [comment]
Danke!!

P.S.: Ich ruf dich aus Thailand an und schimpe laut, wenn die AoA nicht passt (nie würde ich auf die Idee kommen, die Anknüpfung um einen cm zu verändern)!
;))

[Achtung, das ist ein Wiener Scherz!}
