### ISSUE TITLE
Circus 14.01

### ISSUE THREAD

**Issue by DonMaso** [wingworks/Circus-11#4]
Here we go, Circus 14 Specs v1 :)
[Circus 14 v1.pdf](https://github.com/wingworks/Circus-11/files/640950/Circus.14.v1.pdf)

**Comment by wingworks** [comment]
Willst du die beiden Größen gleichzeitig bauen? Dann mache ich den Plan
auch gleich mit fertig. Spart schon einiges an Zeit mehrere Kites
gleichzeitug zu bauen da weniger Umbauzeiten etc.


2016-12-09 2:03 GMT+01:00 Klaus <notifications@github.com>:

**Comment by DonMaso** [comment]
Hallo Karsten,

ja, dachte mir, dass das sinnvoll ist, 11 und 14 gleichzeitig zu nähen. Material für beide Kites habe ich bestellt / ist am Weg.

AUSSERDEM, wenn wir SPECS (AoA, PT und AR) für 9, 11 und 14 gleichzeitig festlegen, sehen wir ev. mehr (wo haben wir Platz, woran sollten wir “drehen” bei der mittleren Kitegrösse - 11).

Bis jetzt hast du nur 14er erhalten, 9 sollte ich dieses Wochenende noch machen.  14 ist “schneller”, weniger weniger AoA, weniger Profiltiefe (ev. noch 0.2—0.5% weniger). Ins Summe weniger Drag (mit relativ leicht grösseren Ohren (durch geringeren cut-out an TE), geringere AR (weil er ohnehin grösser ist).  
Arc für den 14er habe ich mal übernommen, kann man sich noch ansehen, ev. noch flacher im Zentrum (früheres “Losdüsen").  Grösse 14.7 .. 

Bevor ich die genauen Daten für AoA/PT liefere, müssen wir uns über Tubeverlauf unterhalten.  Ich denke, dass 175mm im Zentrum genug sind . Masse für 14er Tube, siehe Vermessung Vegas 14, die funktioniert)! 

Ich hab noch einen 9er Dice, den kann ich auch vermessen (wie geschrieben, ist aber schneller as Vegas). Beim 9er muss ich mir AR, AoA, PT  noch überlegen. Der 9.0 Cirucus ist halt dann für Wind, wenn die Dackel zu fliegen anfangen (bei meinem Geiwicht), daher seltener am Wasser, aber bei mir zuhause am Neusiedlersee kommt er zum pro Jahr 10x zum Einsatz. Für Thailand ist der “nix”! In Vientnam (Mui Ne und Umgebung) soll er funktionieren! 

Nach dem 9er kommt der 6.5er :)

lg
Klaus

**Comment by DonMaso** [comment]
Servus Karsten,

Habe ein Update der Specs auf CAD gezeichnet, jetzt macht es mehr Sinn.  IK hat "scalopped TE" eingestellt .. sieht komisch aus! 
Arc wurde gestreckt, Werte für sweep habe ich gemessen (CAD). Werte für Tube von Vegas 14/Circus 11 und IK (Auto IK) angegeben. Ich würde bei Tube exact die gleichen Werte wie für Cirucs 11 nehmen und einfach verschieben. 

Vorschlag für Profil(tiefe) vs. v4.1 verfeinert. 
AoA Verlauf (Auto IK) für 4.5 bis 6 angegeben.  

Hope this helps. lg K

PS: xls und dwg bei Bedarf, glaube du brauchst das nicht?! 

[Circus-14 (4.2) Specs.xls.pdf](https://github.com/wingworks/Circus-11/files/643180/Circus-14.4.2.Specs.xls.pdf)

**Comment by wingworks** [comment]
Hier nicht relevant, siehe issues Circus 14
