### ISSUE TITLE
Bladder

### ISSUE THREAD

**Issue by wingworks** [wingworks/Circus-11#6]
Aus #2 

4) Bladder, sehe ich richtig, dass du bei deinen Kites kein Auslassventil hast? Würde gerne ein Ventil knapp bei der letzten Strut (4 oder 5) inkludieren.

5) Bladder, wie viel Spielraum (cm) haben wir, um diese Bladder z.B. in einen "Circus 11 (v2)" zu verwursten? M.a.W., lassen sich die Bladders in einer v2 weiterverwenden (Circus 11 (v2) wird rund um Bladder designed? Ist ein AR von zB. 5.5 mit dieser Bladder möglich?

**Comment by wingworks** [comment]
zu 4.
Kein Auslassventil in der Nähe des Tips im DXF vorgesehen. Zuletzt großes Ventil im Center, das hat mir gereicht.

zu 5.
Den Bladder skaliere ich über einen Faktor, so dass er größer ist als die Tube. Den Faktor kann ich beliebig für Durchmesser und Länge anpassen, so dass der Bladder auch in andere Kites (+- 1-2qm) passt. One-Pump macht das aber etwas schwieriger wenn sich die Position der zusätzlich Struts ändert.

**Comment by DonMaso** [comment]
ok, Auslass muss nicht sein!

Skalierung der Bladder würde ich so wählen, dass wir ev. auf AR 5.5 gehen können .. just in case .. klar, one-pump ist dann not so funny .. :)

Durchmesser Tube wird wohl passen!  die struts habe ich nie “nachgerechnet”.  wichtig ist, dass wir den Anfangsdurchmesser min. über 2/3 bis 4/5 beibehalten können.

**Comment by wingworks** [comment]
Ich erstelle eine separate DXF Datei mit den Bladdern

**Comment by DonMaso** [comment]
gracias!

**Comment by wingworks** [comment]
Erledigt.
Release Version 1.1 mit neuer DXF Datei ist hochgeladen
